### ISSUE TITLE
rust-tls

### ISSUE THREAD

**Issue by zhangbtciab** [alexcrichton/curl-rust#478]
how to enable rust-tls and disable default ssl ?

**Comment by sagebind** [comment]
Use the `rustls` crate feature as documented [in the readme](https://github.com/alexcrichton/curl-rust#building):

> - `rustls` Enable SSL/TLS support via [Rustls](https://github.com/ctz/rustls), a well-received alternative TLS backend written in Rust. Rustls is always statically linked. Disabled by default.

It would be best to disable default features when doing so to ensure that OpenSSL is not included. For example:

```toml
[dependencies.curl]
default-features = false
features = ["rustls"]
```
